### ISSUE TITLE
Add support for psy/psysh

### ISSUE THREAD

**Issue by goodevilgenius** [phar-io/phar.io#101]
https://github.com/bobthecow/psysh/ doesn't provide their `phar` releases directly on GitHub, so I can't use `phive install bobthecow/psysh` to install them.

The latest release is available from https://psysh.org/psysh, however (see https://github.com/bobthecow/psysh/wiki/Installation).

But, `phive install https://psysh.org/psysh` results in the error "Could not extract PHAR version from https://psysh.org/psysh".

It would be great if it was supported directly with `phive install psysh`.

**Comment by theseer** [comment]
> [bobthecow/psysh](https://github.com/bobthecow/psysh/) doesn't provide their `phar` releases directly on GitHub, so I can't use `phive install bobthecow/psysh` to install them.

Funny enough, the installation instructions they provide claims it should work. But I fail to see how that could have ever worked given the releases history.
 
> The latest release is available from [psysh.org/psysh](https://psysh.org/psysh), however (see [bobthecow/psysh/wiki/Installation](https://github.com/bobthecow/psysh/wiki/Installation)).
>

That doesn't help, unfortunately: Neither the filename itself nor the mime type used signal in any way it's a phar. It also does not provide any information on the version it might contain and there is no `.asc` file accompanying it. This is basically a  "get this this binary and trust me it's fine"-installation.
 
> But, `phive install https://psysh.org/psysh` results in the error "Could not extract PHAR version from [psysh.org/psysh](https://psysh.org/psysh)".

Makes sense for the aforementioned reasons.

> It would be great if it was supported directly with `phive install psysh`.

Certainly, but there's nothing we can do here to make that work. To get the alias registered, they need to provide a pull request. Such a PR will only get merged though when it actually works, meaning they provide signed phar releases using any of our supported distribution forms.

Sorry, but I'm closing this.

**Comment by goodevilgenius** [comment]
@theseer Thanks for the clarification. Hopefully @bobthecow will be able to make the necessary changes to make it work. There's already an open issue there to make it happen.
