### ISSUE TITLE
Add support for twigcs

### ISSUE THREAD

**Issue by prudloff-insite** [phar-io/phar.io#106]
We use twigcs on our CI and it would be useful to be able to install it with phive.

They provide PHAR files but no signature: https://github.com/friendsoftwig/twigcs/releases

**Comment by theseer** [comment]
You can already do that, sacrificing security:

```
theseer@nyda /tmp/x3 $ phive --home ./home install --force-accept-unsigned friendsoftwig/twigcs
Phive 0.14.5-23-g22f9971 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
Downloading https://api.github.com/repos/friendsoftwig/twigcs/releases?per_page=100
Downloading https://github.com/friendsoftwig/twigcs/releases/download/v5.0.0/twigcs.phar
Linking ./home/phars/friendsoftwig/twigcs-5.0.0.phar to /tmp/x3/tools/twigcs
```

To get an alias registered (e.g. `twigcs`), the project would a) need to sign their phar releases and b) send a PR against our alias db file (https://github.com/phar-io/phar.io/blob/master/data/repositories.xml)

**Comment by prudloff-insite** [comment]
Thanks for the explanation. I asked if they can provide signatures: https://github.com/friendsoftwig/twigcs/issues/182
