### ISSUE TITLE
Releases Link Not Working

### ISSUE THREAD

**Issue by MGatner** [phar-io/phar.io#113]
... appears to be a cert issue? See originating discussion: https://github.com/shivammathur/setup-php/discussions/540

Link in question: https://phar.io/releases/phive.phar

**Comment by theseer** [comment]
Interesting. As `https://phar.io` loads fine for me and didn't trigger any warnings in the TLS monitoring either...

The Link is merely a glorified redirect to whatever is the latest version. Not sure how that could be a problem on our end up i'll investigate.

**Comment by theseer** [comment]
It's now an ngnix  based redirect without lookup to the API, which appears to be working.

**Comment by MGatner** [comment]
Confirmed! Thanks for the fast response.
