### ISSUE TITLE
Add support for Twig-CS-Fixer

### ISSUE THREAD

**Issue by thePanz** [phar-io/phar.io#155]
[Twig-CS-Fixer](https://github.com/VincentLanglet/Twig-CS-Fixer) is available as a phar here:
https://github.com/VincentLanglet/Twig-CS-Fixer/releases/download/3.0.0/twig-cs-fixer.phar

thanks to @VincentLanglet

From the documentation: https://github.com/VincentLanglet/Twig-CS-Fixer?tab=readme-ov-file#as-a-phar
they sign the phar files with GPG too:
> The PHAR files are signed with a public key which can be queried at keys.openpgp.org with the id AC0E7FD8858D80003AA88FF8DEBB71EDE9601234

would it be possible to add this to PHIVE?

**Comment by VincentLanglet** [comment]
PR is wip https://github.com/phar-io/phar.io/pull/154/files

**Comment by VincentLanglet** [comment]
https://github.com/phar-io/phar.io/pull/154/files is merged, you can close the issue @thePanz
