### ISSUE TITLE
Download link still leads to v0.15.2

### ISSUE THREAD

**Issue by cracksalad** [phar-io/phar.io#165]
Version 0.15.3 has been released on 22nd of August but the download link `https://phar.io/releases/phive.phar` (as used in the installation guide on phar.io) still leads to v0.15.2. Could be some kind of caching issue or webserver redirect config, not sure.

**Comment by theseer** [comment]
Fixed. Thank you and Sorry for the inconvenience. I really need to fix my release script to properly update the redirect.
