### ISSUE TITLE
Deployer support

### ISSUE THREAD

**Issue by inverse** [phar-io/phar.io#30]
Repo: https://github.com/deployphp/deployer

Let me know how i can assist

**Comment by theseer** [comment]
Unfortunately, Deployer does not currently satisfy the requirements to be installed via `phive`.

Please check (this guide)[https://phar.io/#distributingPhars] on how to make a project installable via `phive`. As mentioned within the guide, feel free to open a PR to have an alias added afterwards.

For now, there is nothing we can do here.
