### ISSUE TITLE
broken link 404 to Submit your public key to the key servers

### ISSUE THREAD

**Issue by jpuck** [phar-io/phar.io#31]
This page: https://phar.io/howto/uploading-public-keys.html has a broken link to submit your public key to keyservers: https://sks-keyservers.net/i/#submit

The root page is up, but there's no obvious navigation to lead to the correct form now.

**Comment by theseer** [comment]
Thanks for letting us know. We'll update the page as soon as I figured out whether this is a permanent 404 in need of a replacement or only a temporary condition.

**Comment by theseer** [comment]
Okay, looks like this was intentionally [removed](https://git.sumptuouscapital.com/?p=sks-keyservers-pool.git;a=commit;h=b17f1b155bf5e7109d8c40734610a606ae31129a).

So we have to come up with a new link target :)

**Comment by jpuck** [comment]
Thanks!
