### ISSUE TITLE
Multiple repositories for one PHAR

### ISSUE THREAD

**Issue by filips123** [phar-io/phar.io#46]
Is it possible to have multiple repository URL for one PHAR in [`repositories.xml`](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml). This would be useful if one URL will be unavailable, so PHIVE could fallback to another.

**Example:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<repositories xmlns="https://phar.io/repository-list">
    <phar alias="phpunit" composer="phpunit/phpunit">
        <repository url="https://phar.phpunit.de/phive.xml"/>
        <repository type="github" url="https://api.github.com/repos/sebastianbergmann/phpunit/releases" />
    </phar>
</repositories>
```

Also, is it possible to host PHAR on other GIT systems, like GitLab or BitBucket?

**Comment by theseer** [comment]
Duplicate to https://github.com/phar-io/phive/issues/150
