### ISSUE TITLE
Paratest also now available as Phar

### ISSUE THREAD

**Issue by andreasschroth** [phar-io/phar.io#52]
You might consider adding an alias for paratest as well and listing it on your website - starting now (version 2.1) we also have an automatic .phar deployment in place: https://github.com/paratestphp/paratest

**Comment by theseer** [comment]
Thank you for letting us know and congrats for the automation :)

With regards to adding an alias: Feel free to supply a PR for this.
I'd like to refrain from having to choose the alias on behalf of the external project as I consider that the project's task and responsibility.

**Comment by andreasschroth** [comment]
@theseer Thank you for your fast answer. PR submitted. As the contents in `repositories.xml` are not alphabetically ordered, I just added it to the end of the list.

**Comment by theseer** [comment]
Thanks.

Yes, we should probably sort things before it grows even further.
