### ISSUE TITLE
Consider adding drupal-check

### ISSUE THREAD

**Issue by vifito** [phar-io/phar.io#67]
Consider adding drupal-check, built on PHPStan, this static analysis tool will check for correctness (e.g. using a class that doesn't exist), deprecation errors, and more.

https://github.com/mglaman/drupal-check

**Comment by theseer** [comment]
Thank you for opening an issue. Unfortunately, there is nothing we can do for you at this point.

Phar.io does not host or provide any phar files except phive, the phar installer itself.

The project you mentioned does provide an unsigned phar, it can be installed using phive without us needing to do anything. In your case for example using phive install --force-accept-unsigned mglaman/drupal-check should just work.

When the project additionally wants to have an alias (like, say `drupal-check`) to be assigned, all they have to do is open a PR against our alias file.
