### ISSUE TITLE
PHP Mess Detector

### ISSUE THREAD

**Issue by luiz-brandao-jr** [phar-io/phar.io#68]
PHPStorm has built-in support for PHP Mess Detector, it would be interesting to have it available in Phive. https://phpmd.org/

**Comment by theseer** [comment]
You already have: 

```
theseer@nyda /tmp/x7 $ phive install phpmd/phpmd
Phive 0.13.2 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpmd/phpmd/releases
Downloading https://github.com/phpmd/phpmd/releases/download/2.7.0/phpmd.phar
Downloading https://github.com/phpmd/phpmd/releases/download/2.7.0/phpmd.phar.asc
Downloading key 0F9684B8B16B7AB0
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x0F9684B8B16B7AB0
Successfully downloaded key.

	Fingerprint: 3C68 40FC AFFB B059 F283 8A2C 0F96 84B8 B16B 7AB0

	PHPMD (PHP Mess Detector) <pgp@phpmd.org>

	Created: 2019-10-29

Import this key? [y|N] y
Linking /home/theseer/.phive/phars/phpmd/phpmd-2.7.0.phar to /tmp/x7/tools/phpmd
```

If there's an interest in having a short alias for installation (for instance `phive install phpmd`), the project needs to supply a PR against our [alias database file](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml).

While of course we can technically do that, I won't add it without their consent.

**Comment by luiz-brandao-jr** [comment]
Thanks, I ran `phive list` and assumed that was all we had available. I should have read the usage examples more carefully.
