### ISSUE TITLE
Rendering bug related to logo on phar.io website

### ISSUE THREAD

**Issue by sebastianbergmann** [phar-io/phar.io#7]
![screenshot from 2016-03-08 08-31-55](https://cloud.githubusercontent.com/assets/25218/13595041/b2240040-e508-11e5-96e5-624723ac6ff4.png)

I am using Firefox 44.0.2 on Fedora 23.

**Comment by theseer** [comment]
Interesting, but I cannot reproduce/confirm this on my system:

![screenshot from 2016-03-08 12-25-10](https://cloud.githubusercontent.com/assets/111333/13600435/154e2266-e529-11e5-95c4-1f87a1cbd417.png)

**Comment by theseer** [comment]
No feedback provided.
