### ISSUE TITLE
Please add Drush

### ISSUE THREAD

**Issue by Fonata** [phar-io/phar.io#74]
Right now, running `phive install drush-ops/drush` doesn't give me a .phar file. 

I explained why and how I created and tested the .phar file for Drush 10.1.1 here: https://github.com/drush-ops/drush/issues/3331#issuecomment-569980817

**Comment by theseer** [comment]
Thank you for opening an issue. Unfortunately, there is nothing we can do for you at this point.

Phar.io does not host or provide any phar files except `phive`, the phar installer itself.

If you want a phar archive of the application you referenced, you do have to open a ticket with the project that is responsible for it. Once they provide a (preferably signed) phar, it can be installed using `phive` without us needing to do anything.

When the project additionally wants to have an alias (like, say `drush`) to be assigned, all they have to do is [open a PR against our alias file](data/repositories.xml).
