### ISSUE TITLE
Consider adding Zephir

### ISSUE THREAD

**Issue by sergeyklay** [phar-io/phar.io#76]
Hello,

Consider adding support for zephir.phar. 

Zephir - is a high level programming language that eases the creation and maintainability of extensions for PHP. Zephir extensions are exported to C code that can be compiled and optimized by major C compilers such as gcc/clang/vc++. Functionality is exposed to the PHP language.

- [Website](https://zephir-lang.com/)
- [GitHub](https://github.com/phalcon/zephir)
- [Releases has attached PHAR](https://github.com/phalcon/zephir/releases)

**Comment by theseer** [comment]
Thank you for opening an issue. Unfortunately, there is nothing we can do for you at this point.

Phar.io does not host or provide any phar files except phive, the phar installer itself.

The project you mentioned does provide an unsigned phar, it can be installed using phive without us needing to do anything (in your case using `phive install --force-accept-unsigned phalcon/zephir`).

When the project additionally wants to have an alias (like, say `zephir`) to be assigned, all they have to do is open a PR against our alias file.
