### ISSUE TITLE
Provide List of Available Packages (in full)

### ISSUE THREAD

**Issue by davidshq** [phar-io/phar.io#77]
I like Phive, its really easy to use and keeps things neat...but it isn't easy to find out what packages are available for use with Phive.

Sure there is the list on the homepage: https://phar.io/

But this is incomplete, as it states, "many more". I think from a user onboarding standpoint it would be useful to have another button next to "Yours missing?" that says something like, "View Available Packages" or "View Package Repository" that would provide a full list of the available packages.

After searching a bit I stumbled across this listing, which I'm guessing is the complete list?
https://github.com/phar-io/phar.io/blob/master/data/repositories.xml

I think a tool like Phive can make the onboarding of new PHP developers much simpler but that right now the lack of a package listing hampers this, fwiw.

Thanks for your hard work!

**Comment by theseer** [comment]
Thank you for your input. Unfortunately, there's not really much we can do here.

Currently, `phive` comes with four different resolvers, where we only control one: the phar.io registered alias database, which is using the `repositories.xml` file you found. It's content can be shown via `phive list`. We can of course argue on how this list looks...

One of our main design goals was to *not* require any central authority or service to work. So `phive` is deliberately not limited to these aliases: You can install via a github "user-or-group-name/project-name", gitlab "namespace/repository" as well as via standard "https-url". 

You can probably understand that there is no way for us to provide any sort of list for these.
