### ISSUE TITLE
Release redirect broken

### ISSUE THREAD

**Issue by jaapio** [phar-io/phar.io#78]
The at phar.io releases page returns 404. Which breaks our ci currently:

https://phar.io/releases/phive.phar.asc
I checked the script but that seems to be ok to me. Maybe some misconfiguration?

**Comment by theseer** [comment]
*Sigh*

Tl;Dr: Fixed.

What happened?

My bad. I started a draft for the release of 0.14.0. Given that the redirector script uses an Auth-Token to not be restricted in API calls to see the latest release, it now also saw that draft. But the draft doesn't yet have release files attached, so it fell short.

**Comment by jaapio** [comment]
Thanks for the quick response!

We are all humans, making small mistakes. Keep up the good work and please stay safe. 👍
