### ISSUE TITLE
Update the version of PHPMD

### ISSUE THREAD

**Issue by taliptako** [phar-io/phar.io#81]
Only version 2.7 available can you update it to 2.8.2
[https://phpmd.org/](https://phpmd.org/)

**Comment by theseer** [comment]
No, phar.io and phive do not host any phars nor are responsible for releases. We merely provide an installer.

The last signed release of phpmd seems to be 2.7.0. All later versions are are unsigned, as `phive` even clearly prints out:

```
heseer@nyda /tmp/x3 $ phive --home ./phive install phpmd
Phive 0.14.4-6-g956ee5e-dirty - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching repository list
Downloading https://phar.io/data/repositories.xml
Downloading https://api.github.com/repos/phpmd/phpmd/releases
[WARNING]  phpmd 2.8.2: No GPG Signature 
[WARNING]  phpmd 2.8.1: No GPG Signature 
[WARNING]  phpmd 2.8.0: No GPG Signature 
[WARNING]  phpmd 2.8.0-beta.2: No GPG Signature 
[WARNING]  phpmd 2.8.0-beta.1: No GPG Signature 
Downloading https://github.com/phpmd/phpmd/releases/download/2.7.0/phpmd.phar
Downloading https://github.com/phpmd/phpmd/releases/download/2.7.0/phpmd.phar.asc
[...]
```

Feel free to talk to the phpmd maintainers to request signatures on later releases or decide to install untrusted and unchecked versions by using `--force-accept-unsigned`.

There's nothing we can do here.
