### ISSUE TITLE
Release linked to not latest release

### ISSUE THREAD

**Issue by rask** [phar-io/phar.io#82]
When I use `wget -O phive.phar https://phar.io/releases/phive.phar` I receive version `0.13.2`, while the newer Phive version at GitHub is `0.14.*`.

We're getting some errors with our tool installations with the `0.13.2`. version, and the problem is fixed in some later version, but we would not like to hard code a version to fix this.

Thanks!

**Comment by theseer** [comment]
I cannot confirm this:

```
$ curl https://phar.io/releases/phive.phar
Forwarded to https://github.com/phar-io/phive/releases/download/0.14.4/phive-0.14.4.phar
```

```
$ wget -O phive.phar https://phar.io/releases/phive.phar

--2020-08-26 16:46:21--  https://phar.io/releases/phive.phar
Resolving phar.io (phar.io)... 188.94.27.6
Connecting to phar.io (phar.io)|188.94.27.6|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/phar-io/phive/releases/download/0.14.4/phive-0.14.4.phar [following]
[...]
```


```
theseer@nyda ~ $ php ./phive.phar --version
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
```

Looks all good to me?

**Comment by theseer** [comment]
> We're getting some errors with our tool installations with the 0.13.2. version, and the problem is fixed in some later version, but we would not like to hard code a version to fix this.

Not an optimal solution, but you could, if you have `phive` already, use the self-update command as a workaround:
```
theseer@nyda ~ $ php ./phive.phar self-update
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
Downloading https://api.github.com/repos/phar-io/phive/releases
You already have the newest version of PHIVE.
```

**Comment by rask** [comment]
Hmm, might be some of our network things caching it too aggressively or something, need to investigate.

Will try that self-update and see if that is a sensible option for now.

Thanks!

**Comment by theseer** [comment]
I guess this can be closed as the release redirector link works as advertised and the OP didn't add anything thing here anymore.

@rask If you think there still is a problem, please add a comment.
