### ISSUE TITLE
Show full list of supported tools on website

### ISSUE THREAD

**Issue by jan-di** [phar-io/phar.io#96]
Currently the website shows a few tools and states that "many more" are supported, but there are no instructions on the website on how to find the complete list of tools.

The easiest solution would be to link to https://github.com/phar-io/phar.io/blob/master/data/repositories.xml on the website.

**Comment by theseer** [comment]
Problem is, even that list is incomplete as it only lists the aliases - which is only a fraction of tools. Phive technically can install everything that is hosted via github releases, gitlab releases or even via a traditional https url. There is no dependency to a central registry.

For pure convenience (and to support fully custom hosted solutions), we provide an alias registry - the very file you mention. 

I'm thus not sure how we could fulfill your request :)

**Comment by theseer** [comment]
No Feedback provided.
