### ISSUE TITLE
Add Doctum to the main webpage ?

### ISSUE THREAD

**Issue by williamdes** [phar-io/phar.io#98]
Hi,

I just found out your website and I would like to add [Doctum](https://github.com/code-lts/doctum#readme) to it because I provide a PHAR.

Thanks :)

**Comment by theseer** [comment]
As far as I can tell, there is no alias for it yet, right?

Maybe you want to create a PR against our Alias [repository.xml](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml).

We'll see about the home page ;)

**Comment by williamdes** [comment]
> As far as I can tell, there is no alias for it yet, right?
> 
> Maybe you want to create a PR against our Alias [repository.xml](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml).
> 
> We'll see about the home page ;)

Here is is with bonus fixes ;)
See: https://github.com/phar-io/phar.io/pull/99
